{% set version = '2.0.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-remotes
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/remotes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/remotes/remotes_{{ version }}.tar.gz
  sha256: aab33b1d1ec24a1a7656c3b2c9ec69227b24ab01163bd9348da1e4cb61ed5267

build:
  merge_build_host: True  # [win]
  number: 1000
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('remotes')"           # [not win]
    - "\"%R%\" -e \"library('remotes')\""  # [win]

about:
  home: https://github.com/r-lib/remotes#readme
  license: GPL (>= 2)
  summary: Download and install R packages stored in 'GitHub', 'BitBucket', or plain 'subversion'
    or 'git' repositories. This package is a lightweight replacement of the 'install_*'
    functions in 'devtools'. Indeed most of the code was copied over from 'devtools'.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast

# Package: remotes
# Title: R Package Installation from Remote Repositories, Including 'GitHub'
# Version: 2.0.2
# Authors@R: c( person("Gabor", "Csardi", , "csardi.gabor@gmail.com", role = c("aut", "cre")), person("Hadley", "Wickham", role = c("aut")), person("Winston", "Chang", role = "aut"), person("Jim", "Hester", role = "aut"), person("RStudio", role = "cph"), person("Martin", "Morgan", role = "aut"), person("Dan", "Tenenbaum", role = "aut"), person("Mango Solutions", role = "cph") )
# Description: Download and install R packages stored in 'GitHub', 'BitBucket', or plain 'subversion' or 'git' repositories. This package is a lightweight replacement of the 'install_*' functions in 'devtools'. Indeed most of the code was copied over from 'devtools'.
# License: GPL (>= 2)
# URL: https://github.com/r-lib/remotes#readme
# BugReports: https://github.com/r-lib/remotes/issues
# Imports: methods, utils
# Suggests: curl, covr, git2r (>= 0.23.0), knitr, mockery, pkgbuild (>= 1.0.1), pingr, rmarkdown, testthat, withr
# Depends: R (>= 3.0.0)
# VignetteBuilder: knitr
# RoxygenNote: 6.1.0
# SystemRequirements: Subversion for install_svn, git for install_git
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2018-10-30 10:46:53 UTC; gaborcsardi
# Author: Gabor Csardi [aut, cre], Hadley Wickham [aut], Winston Chang [aut], Jim Hester [aut], RStudio [cph], Martin Morgan [aut], Dan Tenenbaum [aut], Mango Solutions [cph]
# Maintainer: Gabor Csardi <csardi.gabor@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-10-30 11:30:10 UTC
