travis:
  secure:
    BINSTAR_TOKEN: Cu1HQEh9Bh1ZrOCKTAgfeT1nTpXuta0UHzyyDIeNiG+df+a+B7heJcY8y936KAzQRkaNe4eT4fP/ssDq9Wyt03qLwqwhvDn1YnJtdfbWMegKpp54ShJEbdEuZpGQfo7aOTc8CzMcwop+N8zEUfBpzthOsQRI1PcP/exhO/occVZrs576k+jtKWV1+6Kl7sMcC+TCmuxZhgldSoAVJ93WDWpO/TLFI/LIO6cyPjDkHDXf/Abyxc2lPEdQnj6PDpc1tPCcsmCBrbI0lkiqCHcVoBO+JginNnSFsT/S4K2AxslzGajD8SPlmshy4VEchWFRQtELDWbbkj2tScV0T6KTkiHmGaAxzSd6DAeKPzBxE+YjVI/21mLVWejs8Xuo8WmQU4Rty7OIGKoF2J87NcW7vhFOeBVOPLW/grbJU1dmsBr44zxtISijZf+alhaRu+uQfN5RBYfsmZEK7dB/xZNyLvh8wJ6hlQx0lxswVCPOxZQxY899s5F52/1gBdqK+B2K47p2y8INuDkaYWUoEKcz1cWE014s8cfOCTyqhmvaL6bMnyBxBMcUW9uTSe6oqhME+NObPP0OA9ok241kHARqkthZOIVPTWZlllDi4sp6xZ9yN7DCYnrrvnL/UQZsbHIdKlEb0akiuJcy+0FWM0JyP602nLxRMAAotfKM6KG6koU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
